apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  namespace: monitoring
  name: k8s
spec:
  storage:
    # This determines the maximum number of bytes that storage blocks can use
    # (note that this does not include the WAL size, which can be substantial)
    retensionSize: 3GB
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 4Gi
